from enum import Enum


class PurchaseError(Enum):
    NO_ERROR = 'No error'
    EMPTY_CURRENCY = 'Empty currency'
    INVALID_CURRENCY = 'Invalid currency'
    EMPTY_GENDER = 'Empty gender'
    INVALID_GENDER = 'Invalid gender'
    EMPTY_FIRST_NAME = 'Empty first name'
    EMPTY_LAST_NAME = 'Empty last name'
    EMPTY_FULL_NAME = 'Empty full name'
    INVALID_FULL_NAME = 'Invalid full name'
    EMPTY_EMAIL = 'Empty email'
    INVALID_EMAIL = 'Invalid email format'
    EMPTY_PHONE = 'Empty phone number'
    EMPTY_WEEK_DAY = 'Empty week day'
    INVALID_WEEK_DAY = 'Invalid week day'
    EMPTY_WEEK_DAY_NUMBER = 'Empty week day number'
    INVALID_WEEK_DAY_NUMBER = 'Invalid week day number'
    NEGATIVE_TAXFUL_TOTAL = 'Negative value of tax full'
    INVALID_TAXFUL_TOTAL = 'Invalid tax full value'
    NEGATIVE_TAXLES_TOTAL = 'Negative value of tax les'
    INVALID_TAXLES_TOTAL = 'Invalid tax les value'
    NEGATIVE_QUANTITY_TOTAL = 'Negative value of total quantity'
    INVALID_QUANTITY_TOTAL = 'Invalid total quantity value'
    NEGATIVE_UNIQ_TOTAL = 'Negative value of unique quantity'
    INVALID_UNIQ_TOTAL = 'Invalid unique quantity value'
    INVALID_MANUFACTURED = 'Invalid manufactured collection'
    EMPTY_MANUFACTURED = 'Empty manufactured collection'
    INVALID_CATEGORY = 'Invalid category collection'
    EMPTY_CATEGORY = 'Empty category collection'
    INVALID_SKU = 'Invalid sku collection'
    EMPTY_SKU = 'Empty sku collection'


class ProductError(Enum):
    NO_ERROR = 'No error'
    INVALID_BASE_PRICE = 'Invalid base price'
    INVALID_BASE_UNIT_PRICE = 'Invalid base unit price'
    INVALID_DISCOUNT_PERCENT = 'Invalid discount percent'
    INVALID_QUANTITY = 'Invalid quantity'
    EMPTY_MANUFACTURER = 'Empty manufacturer'
    INVALID_TAX_AMOUNT = 'Invalid tax amount'
    EMPTY_CATEGORY = 'Empty category'
    EMPTY_SKU = 'Empty sku'
    INVALID_SKU = 'Invalid sku'
    INVALID_TAXLESS_PRICE = 'Invalid taxles price'
    INVALID_TAXFUL_PRICE = 'Invalid taxfull price'
    INVALID_MIN_PRICE = 'Invalid min price'
    INVALID_UNIT_DISCOUNT_AMOUNT = 'Invalid unit discount amount'
    INVALID_DISCOUNT_AMOUNT = 'Invalid discount amount'
    INVALID_PRICE = 'Invalid price'
    INCORRECT_PRICE_CALCULATION = 'Incorrect price calculation'
